import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";
import { Activity, ArrowDownLeft, ArrowUpLeft, BookOpen, Bot, CalendarDays, Check, CheckCircle2, ChevronLeft, CirclePlus, Clock3, CreditCard, Flame, FolderKanban, Heart, HeartHandshake, Image, Languages, Lightbulb, LockKeyhole, MessageCircle, Mic, MoreHorizontal, NotebookPen, Pause, Pencil, Play, Plus, ReceiptText, Search, ShieldCheck, Sparkles, Star, Target, Trash2, TrendingUp, WalletCards, X } from "lucide-react";
import LifeShell from "../components/LifeShell";
import { createId, todayLabel, useLocalList } from "../lib/store";

type Task = { id: string; title: string; area: string; due: string; priority: "عالي" | "متوسط" | "هادئ"; done: boolean };
type EventItem = { id: string; title: string; date: string; time: string; place: string };
type Note = { id: string; title: string; body: string; tag: string; createdAt: string };
type Transaction = { id: string; title: string; amount: number; type: "income" | "expense"; category: string; date: string };
type Habit = { id: string; title: string; detail: string; streak: number; done: boolean };

const initialTasks: Task[] = [
  { id: "t1", title: "مراجعة خطة الأسبوع وترتيب الأولويات", area: "التركيز", due: "اليوم", priority: "عالي", done: false },
  { id: "t2", title: "إنهاء جلسة اللغة الألمانية", area: "التعلّم", due: "اليوم", priority: "متوسط", done: false },
  { id: "t3", title: "تسجيل المصروفات الأخيرة", area: "الماليات", due: "غدًا", priority: "هادئ", done: true },
];

const initialEvents: EventItem[] = [
  { id: "e1", title: "جلسة تركيز عميق", date: "اليوم", time: "09:30", place: "مساحتك الخاصة" },
  { id: "e2", title: "موعد العائلة", date: "اليوم", time: "18:00", place: "البيت" },
  { id: "e3", title: "مراجعة الأهداف الشهرية", date: "غدًا", time: "11:00", place: "المكتب" },
];

const initialTransactions: Transaction[] = [
  { id: "m1", title: "جلسة تدريس خاصة", amount: 350, type: "income", category: "عمل", date: "اليوم" },
  { id: "m2", title: "اشتراك أدوات التصميم", amount: 24, type: "expense", category: "اشتراكات", date: "أمس" },
  { id: "m3", title: "مشتريات المنزل", amount: 63, type: "expense", category: "البيت", date: "أمس" },
];

const initialHabits: Habit[] = [
  { id: "h1", title: "صلاة الفجر في وقتها", detail: "بداية هادئة ومباركة", streak: 6, done: true },
  { id: "h2", title: "قراءة 10 صفحات", detail: "كتابك الحالي", streak: 4, done: false },
  { id: "h3", title: "ماء وحركة", detail: "ثمانية أكواب + مشي", streak: 9, done: false },
];

export function Home() {
  const [, navigate] = useLocation();
  const [tasks] = useLocalList<Task>("aba-tasks", initialTasks);
  const completed = tasks.filter((task) => task.done).length;
  return <LifeShell title="مساحتك الخاصة" eyebrow="صباحك يبدأ من هنا"><div className="page-stack">
    <section className="hero-panel"><div className="hero-orbit" /><div className="hero-copy"><span className="eyebrow"><Sparkles size={14} /> نظام تشغيل حياتك</span><h1>مساحة واحدة،<br /><span>لحياة أكثر اتزانًا.</span></h1><p>كل ما يهمك في مكان هادئ وواضح؛ من أول فكرة صباحية حتى آخر إنجاز في يومك.</p><div className="hero-actions"><button className="primary-button" onClick={() => navigate("/tasks?add=1")}><CirclePlus size={17} />أضف خطوة اليوم</button><button className="ghost-button" onClick={() => navigate("/analytics")}><TrendingUp size={16} />شاهد إيقاعك</button></div></div><div className="hero-clock"><small>اليوم</small><strong>{new Intl.DateTimeFormat("ar-EG", { day: "numeric" }).format(new Date())}</strong><span>{new Intl.DateTimeFormat("ar-EG", { month: "long" }).format(new Date())}</span><i>{todayLabel()}</i></div></section>
    <section className="stats-grid"><StatCard icon={CheckCircle2} label="خطوات منجزة" value={`${completed} / ${tasks.length}`} detail="إيقاع جيد اليوم" tone="sky" /><StatCard icon={Target} label="تركيز اليوم" value="72%" detail="أعلى من الأمس" tone="violet" /><StatCard icon={Heart} label="طاقة هادئة" value="8.4" detail="من أصل 10" tone="emerald" /></section>
    <section className="section-heading"><div><span className="eyebrow">لقطة اليوم</span><h2>ما يحتاج انتباهك الآن</h2></div><button className="text-button" onClick={() => navigate("/tasks")}>كل المهام <ChevronLeft size={15} /></button></section>
    <section className="dashboard-grid"><div className="panel timeline-panel"><div className="panel-heading"><div><strong>خطك الزمني</strong><small>خطوة واحدة في كل مرة</small></div><Clock3 size={18} /></div>{tasks.slice(0, 3).map((task) => <div className={`timeline-row ${task.done ? "is-done" : ""}`} key={task.id}><span className="timeline-dot" /><div><strong>{task.title}</strong><small>{task.area} · {task.due}</small></div><button className="round-check" onClick={() => toast(task.done ? "الخطوة مكتملة" : "افتح المهام لإكمال الخطوة")}><Check size={14} /></button></div>)}</div><div className="panel motivation-panel"><span className="quote-mark">“</span><p>لا تحتاج أن تنجز كل شيء اليوم. تحتاج فقط أن تختار الشيء الذي يستحق حضورك الآن.</p><div className="quote-author"><span className="avatar">هـ</span><small>تذكير من مساحتك</small></div></div></section>
    <section className="section-heading"><div><span className="eyebrow">مجالاتك</span><h2>كل جانب له مساحته</h2></div><button className="text-button" onClick={() => navigate("/more")}>استكشف <ChevronLeft size={15} /></button></section>
    <section className="areas-grid"><AreaCard href="/tasks" icon={CheckCircle2} title="التركيز" detail="مهام ومشاريع واضحة" tone="blue" navigate={navigate} /><AreaCard href="/habits" icon={Flame} title="النمو" detail="عادات صغيرة، أثر كبير" tone="amber" navigate={navigate} /><AreaCard href="/spiritual" icon={HeartHandshake} title="الروح" detail="عبادتك في متناولك" tone="rose" navigate={navigate} /><AreaCard href="/finance" icon={WalletCards} title="الماليات" detail="وضوح في كل قرار" tone="emerald" navigate={navigate} /><AreaCard href="/deutsch" icon={Languages} title="التعلّم" detail="Deutsch lernen" tone="cyan" navigate={navigate} /><AreaCard href="/memories" icon={Image} title="الذكريات" detail="احتفظ بما لا ينسى" tone="violet" navigate={navigate} /></section>
  </div></LifeShell>;
}

export function Tasks() {
  const [location, navigate] = useLocation();
  const [tasks, setTasks] = useLocalList<Task>("aba-tasks", initialTasks);
  const [title, setTitle] = useState("");
  const [area, setArea] = useState("التركيز");
  const [filter, setFilter] = useState<"all" | "open" | "done">("all");
  const [adding, setAdding] = useState(new URLSearchParams(location.split("?")[1] || "").has("add"));
  useEffect(() => { if (new URLSearchParams(location.split("?")[1] || "").has("add")) setAdding(true); }, [location]);
  const visible = tasks.filter((task) => filter === "all" || (filter === "done" ? task.done : !task.done));
  const add = () => { if (!title.trim()) return toast("اكتب اسم المهمة أولًا"); setTasks((current) => [{ id: createId(), title: title.trim(), area, due: "اليوم", priority: "متوسط", done: false }, ...current]); setTitle(""); setAdding(false); toast("أضيفت المهمة إلى يومك"); };
  return <LifeShell title="المهام" eyebrow="تركيز بدون ضوضاء"><div className="page-stack"><PageIntro kicker="مساحة التركيز" title="أنجز المهم، واترك الباقي." description="قائمة واضحة تساعدك على تحويل النية إلى خطوة قابلة للإنجاز." icon={CheckCircle2} tone="blue"><button className="primary-button" onClick={() => setAdding(true)}><Plus size={17} />مهمة جديدة</button></PageIntro><div className="toolbar"><div className="segmented">{([["all", "الكل"], ["open", "مفتوحة"], ["done", "منجزة"]] as const).map(([key, label]) => <button className={filter === key ? "selected" : ""} onClick={() => setFilter(key)} key={key}>{label}</button>)}</div><span className="muted">{tasks.filter((task) => !task.done).length} خطوات متبقية</span></div><div className="list-panel">{visible.map((task) => <div className={`task-row ${task.done ? "is-done" : ""}`} key={task.id}><button className="task-check" onClick={() => setTasks((current) => current.map((item) => item.id === task.id ? { ...item, done: !item.done } : item))}>{task.done && <Check size={15} />}</button><div className="task-main"><strong>{task.title}</strong><small>{task.area} · {task.due}</small></div><span className={`priority ${task.priority === "عالي" ? "high" : task.priority === "متوسط" ? "medium" : "low"}`}>{task.priority}</span><button className="delete-button" onClick={() => setTasks((current) => current.filter((item) => item.id !== task.id))}><Trash2 size={15} /></button></div>)}{visible.length === 0 && <EmptyState title="كل شيء مرتب" text="لا توجد مهام في هذا العرض." icon={CheckCircle2} />}</div>{adding && <Modal title="مهمة جديدة" onClose={() => setAdding(false)}><div className="form-stack"><label>اسم المهمة<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="مثال: مراجعة عرض المشروع" /></label><label>المجال<select value={area} onChange={(event) => setArea(event.target.value)}><option>التركيز</option><option>التعلّم</option><option>البيت</option><option>العائلة</option></select></label><button className="primary-button full" onClick={add}>حفظ المهمة</button></div></Modal>}</div></LifeShell>;
}

export function Calendar() {
  const [location] = useLocation();
  const [events, setEvents] = useLocalList<EventItem>("aba-events", initialEvents);
  const [adding, setAdding] = useState(new URLSearchParams(location.split("?")[1] || "").has("add"));
  const [draft, setDraft] = useState({ title: "", time: "09:00", place: "" });
  const add = () => { if (!draft.title.trim()) return toast("اكتب اسم الموعد أولًا"); setEvents((current) => [...current, { id: createId(), title: draft.title.trim(), date: "غدًا", time: draft.time, place: draft.place || "مساحتك الخاصة" }]); setDraft({ title: "", time: "09:00", place: "" }); setAdding(false); toast("تم حفظ الموعد"); };
  return <LifeShell title="المواعيد" eyebrow="وقتك يستحق مساحة"><div className="page-stack"><PageIntro kicker="إيقاع اليوم" title="اجعل وقتك يعمل معك." description="مواعيدك وخططك أمامك بإيقاع بصري هادئ." icon={CalendarDays} tone="cyan"><button className="primary-button" onClick={() => setAdding(true)}><Plus size={17} />موعد جديد</button></PageIntro><div className="calendar-layout"><div className="calendar-card"><div className="calendar-month"><button className="icon-button"><ChevronLeft size={16} /></button><strong>{new Intl.DateTimeFormat("ar-EG", { month: "long", year: "numeric" }).format(new Date())}</strong><button className="icon-button"><ChevronLeft size={16} className="flip" /></button></div><div className="calendar-days">{["س", "ح", "ن", "ث", "ر", "خ", "ج"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-numbers">{Array.from({ length: 30 }, (_, index) => <button className={index === new Date().getDate() - 1 ? "today" : ""} key={index}>{index + 1}</button>)}</div></div><div className="list-panel event-list"><div className="panel-heading"><div><strong>القادم</strong><small>مواعيدك القريبة</small></div><CalendarDays size={18} /></div>{events.map((event) => <div className="event-row" key={event.id}><div className="event-time"><strong>{event.time}</strong><small>{event.date}</small></div><div className="event-line" /><div className="event-main"><strong>{event.title}</strong><small>{event.place}</small></div><button className="delete-button" onClick={() => setEvents((current) => current.filter((item) => item.id !== event.id))}><Trash2 size={14} /></button></div>)}</div></div>{adding && <Modal title="موعد جديد" onClose={() => setAdding(false)}><div className="form-stack"><label>اسم الموعد<input autoFocus value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="مثال: مكالمة مع العائلة" /></label><div className="form-row"><label>الوقت<input type="time" value={draft.time} onChange={(event) => setDraft({ ...draft, time: event.target.value })} /></label><label>المكان<input value={draft.place} onChange={(event) => setDraft({ ...draft, place: event.target.value })} placeholder="المكتب" /></label></div><button className="primary-button full" onClick={add}>حفظ الموعد</button></div></Modal>}</div></LifeShell>;
}

export function Finance() {
  const [transactions, setTransactions] = useLocalList<Transaction>("aba-finance", initialTransactions);
  const [adding, setAdding] = useState<"income" | "expense" | null>(null);
  const [draft, setDraft] = useState({ title: "", amount: "", category: "عام" });
  const summary = useMemo(() => transactions.reduce((acc, item) => ({ income: acc.income + (item.type === "income" ? item.amount : 0), expense: acc.expense + (item.type === "expense" ? item.amount : 0) }), { income: 0, expense: 0 }), [transactions]);
  const save = () => { const amount = Number(draft.amount); if (!draft.title.trim() || !Number.isFinite(amount) || amount <= 0) return toast("أكمل وصف الحركة والمبلغ"); setTransactions((current) => [{ id: createId(), title: draft.title.trim(), amount, type: adding || "expense", category: draft.category, date: "اليوم" }, ...current]); setDraft({ title: "", amount: "", category: "عام" }); setAdding(null); toast("تم حفظ الحركة المالية"); };
  const formatter = new Intl.NumberFormat("ar-EG", { maximumFractionDigits: 2 });
  return <LifeShell title="مالياتي" eyebrow="وضوح وطمأنينة في قراراتك"><div className="page-stack"><PageIntro kicker="الصورة المالية" title="اعرف أين يذهب مالك." description="كل مبلغ له وجهة واضحة، وكل قرار يبدأ بتسجيله." icon={WalletCards} tone="emerald"><button className="primary-button green" onClick={() => setAdding("income")}><Plus size={17} />إضافة دخل</button></PageIntro><section className="stats-grid finance-stats"><StatCard icon={WalletCards} label="الرصيد الحالي" value={`${formatter.format(summary.income - summary.expense)} ج.م`} detail="المتاح حتى الآن" tone="violet" /><StatCard icon={ArrowUpLeft} label="إجمالي الدخل" value={`${formatter.format(summary.income)} ج.م`} detail="المسجل حاليًا" tone="emerald" /><StatCard icon={ArrowDownLeft} label="إجمالي المصروف" value={`${formatter.format(summary.expense)} ج.م`} detail="تم تسجيله" tone="rose" /></section><div className="finance-actions"><button className="ghost-button" onClick={() => setAdding("income")}><ArrowUpLeft size={16} />إضافة دخل</button><button className="ghost-button danger" onClick={() => setAdding("expense")}><ArrowDownLeft size={16} />إضافة مصروف</button></div><div className="list-panel"><div className="panel-heading"><div><strong>آخر الحركات</strong><small>سجّل أي حركة أولًا بأول</small></div><ReceiptText size={18} /></div>{transactions.map((item) => <div className="transaction-row" key={item.id}><span className={`transaction-icon ${item.type === "income" ? "income" : "expense"}`}>{item.type === "income" ? <ArrowUpLeft size={16} /> : <ArrowDownLeft size={16} />}</span><div className="task-main"><strong>{item.title}</strong><small>{item.category} · {item.date}</small></div><b className={item.type === "income" ? "amount-income" : "amount-expense"}>{item.type === "income" ? "+" : "−"} {formatter.format(item.amount)} ج.م</b><button className="delete-button" onClick={() => setTransactions((current) => current.filter((entry) => entry.id !== item.id))}><Trash2 size={14} /></button></div>)}</div>{adding && <Modal title={adding === "income" ? "إضافة دخل" : "إضافة مصروف"} onClose={() => setAdding(null)}><div className="form-stack"><label>الوصف<input autoFocus value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="مثال: عمل حر" /></label><div className="form-row"><label>المبلغ<input type="number" min="0" value={draft.amount} onChange={(event) => setDraft({ ...draft, amount: event.target.value })} placeholder="0" /></label><label>التصنيف<input value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })} placeholder="عام" /></label></div><button className="primary-button full" onClick={save}>حفظ الحركة</button></div></Modal>}</div></LifeShell>;
}

export function Notes() {
  const [location] = useLocation();
  const [notes, setNotes] = useLocalList<Note>("aba-notes", [{ id: "n1", title: "فكرة تستحق العودة", body: "اجعل لكل يوم مساحة صغيرة لشيء يرفع جودة الحياة.", tag: "فكرة", createdAt: "اليوم" }]);
  const [adding, setAdding] = useState(new URLSearchParams(location.split("?")[1] || "").has("add"));
  const [draft, setDraft] = useState({ title: "", body: "", tag: "فكرة" });
  const save = () => { if (!draft.title.trim() || !draft.body.trim()) return toast("أكمل عنوان الملاحظة ومحتواها"); setNotes((current) => [{ id: createId(), ...draft, createdAt: "اليوم" }, ...current]); setDraft({ title: "", body: "", tag: "فكرة" }); setAdding(false); toast("تم حفظ الملاحظة"); };
  return <LifeShell title="الملاحظات" eyebrow="التقط الفكرة قبل أن تفلت"><div className="page-stack"><PageIntro kicker="مختبر الأفكار" title="كل فكرة تبدأ كسطر." description="دفتر خفيف يلتقط ملاحظاتك من غير ما يقطع إيقاعك." icon={NotebookPen} tone="amber"><button className="primary-button amber" onClick={() => setAdding(true)}><Plus size={17} />ملاحظة جديدة</button></PageIntro><div className="notes-grid">{notes.map((note) => <article className="note-card" key={note.id}><div className="note-top"><span>{note.tag}</span><button className="delete-button" onClick={() => setNotes((current) => current.filter((item) => item.id !== note.id))}><Trash2 size={14} /></button></div><h3>{note.title}</h3><p>{note.body}</p><small>{note.createdAt}</small></article>)}</div>{adding && <Modal title="ملاحظة جديدة" onClose={() => setAdding(false)}><div className="form-stack"><label>العنوان<input autoFocus value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><label>المحتوى<textarea rows={5} value={draft.body} onChange={(event) => setDraft({ ...draft, body: event.target.value })} /></label><label>النوع<input value={draft.tag} onChange={(event) => setDraft({ ...draft, tag: event.target.value })} /></label><button className="primary-button full amber" onClick={save}>حفظ الملاحظة</button></div></Modal>}</div></LifeShell>;
}

export function Habits() {
  const [habits, setHabits] = useLocalList<Habit>("aba-habits", initialHabits);
  const done = habits.filter((habit) => habit.done).length;
  return <LifeShell title="العادات" eyebrow="النمو الهادئ يتراكم"><div className="page-stack"><PageIntro kicker="إيقاع النمو" title="العادات الصغيرة تصنع النسخة الكبيرة منك." description="لا تبحث عن المثالية؛ ابحث عن تكرار يمكن أن تحبه." icon={Flame} tone="amber"><span className="progress-pill"><Flame size={15} />{done} من {habits.length} اليوم</span></PageIntro><div className="habit-grid">{habits.map((habit) => <button className={`habit-card ${habit.done ? "is-done" : ""}`} key={habit.id} onClick={() => setHabits((current) => current.map((item) => item.id === habit.id ? { ...item, done: !item.done, streak: item.done ? Math.max(0, item.streak - 1) : item.streak + 1 } : item))}><span className="habit-check">{habit.done && <Check size={15} />}</span><span className="habit-copy"><strong>{habit.title}</strong><small>{habit.detail}</small></span><span className="streak"><Flame size={15} />{habit.streak}<small>أيام</small></span></button>)}</div><div className="panel insight-panel"><Sparkles size={20} /><div><strong>ملاحظة لطيفة</strong><p>الاستمرارية لا تعني أن كل يوم مثالي؛ تعني أن لديك طريقًا تعود إليه.</p></div></div></div></LifeShell>;
}

export function Spiritual() { const [count, setCount] = useState(33); return <LifeShell title="عبادتي" eyebrow="سكينة تملأ يومك"><div className="page-stack"><PageIntro kicker="مساحة الروح" title="قليل دائم، خير من كثير منقطع." description="مساحة هادئة لوردك وذكرك ونواياك اليومية." icon={HeartHandshake} tone="rose"><span className="progress-pill rose"><Heart size={15} />ورد اليوم 68%</span></PageIntro><div className="spiritual-grid"><div className="panel quran-card"><BookOpen size={22} /><span className="eyebrow">وردك اليوم</span><h2>وَقُلْ رَبِّ زِدْنِي عِلْمًا</h2><p>سورة طه · الآية 114</p><button className="ghost-button" onClick={() => toast("نبدأ من حيث أنت")}><Play size={15} />ابدأ القراءة</button></div><div className="panel dhikr-card"><span className="eyebrow">الذكر</span><h3>سبّح بهدوء</h3><div className="dhikr-count">{count}</div><button className="primary-button rose" onClick={() => setCount((value) => value >= 99 ? 0 : value + 1)}>تسبيحة جديدة</button><small>من أصل 99</small></div></div><div className="list-panel"><div className="panel-heading"><div><strong>مساحات اليوم</strong><small>نية، صلاة، وامتنان</small></div><HeartHandshake size={18} /></div>{["صلاة الفجر", "صفحة من القرآن", "ثلاثة أشياء ممتن لها"].map((item, index) => <div className="task-row" key={item}><span className={`task-check static ${index < 2 ? "checked" : ""}`}>{index < 2 && <Check size={15} />}</span><div className="task-main"><strong>{item}</strong><small>{index < 2 ? "تمت اليوم" : "حين يهدأ المساء"}</small></div></div>)}</div></div></LifeShell>; }

export function Memories() { const [memories, setMemories] = useLocalList<{ id: string; title: string; detail: string; color: string }>("aba-memories", [{ id: "mm1", title: "يوم بسيط وجميل", detail: "منذ 3 أيام", color: "violet" }, { id: "mm2", title: "ضحكة العائلة", detail: "منذ أسبوع", color: "rose" }, { id: "mm3", title: "أول خطوة", detail: "منذ شهر", color: "cyan" }]); return <LifeShell title="ذكريات لا تُنسى" eyebrow="ما يستحق أن يبقى"><div className="page-stack"><PageIntro kicker="أرشيف القلب" title="احتفظ بما لا تريد أن تنساه." description="لا تحتاج الصورة أن تكون مثالية؛ يكفي أنها تعيد لك الشعور." icon={Image} tone="pink"><button className="primary-button pink" onClick={() => { setMemories((current) => [{ id: createId(), title: "لحظة جديدة", detail: "اليوم", color: "pink" }, ...current]); toast("أضيفت ذكرى جديدة"); }}><Plus size={17} />أضف ذكرى</button></PageIntro><div className="memory-grid">{memories.map((memory) => <article className={`memory-card ${memory.color}`} key={memory.id}><div className="memory-visual"><Image size={30} /><span>مساحة صورة</span></div><div className="memory-bottom"><div><strong>{memory.title}</strong><small>{memory.detail}</small></div><button className="delete-button" onClick={() => setMemories((current) => current.filter((item) => item.id !== memory.id))}><Trash2 size={14} /></button></div></article>)}</div></div></LifeShell>; }

export function Analytics() { return <LifeShell title="إيقاعك" eyebrow="افهم يومك بلطف"><div className="page-stack"><PageIntro kicker="لوحة الإيقاع" title="أرقام تساعدك، لا تحكم عليك." description="نظرة مختصرة على طريقة حضورك في مجالاتك." icon={Activity} tone="violet" /><div className="analytics-grid"><StatCard icon={Target} label="تركيز الأسبوع" value="78%" detail="+12% من الأسبوع السابق" tone="violet" /><StatCard icon={Flame} label="أيام متتالية" value="9" detail="أفضل سلسلة هذا الشهر" tone="amber" /><StatCard icon={Heart} label="مساحة هادئة" value="6.2h" detail="وقت بلا تشتيت" tone="rose" /></div><div className="panel chart-panel"><div className="panel-heading"><div><strong>مؤشر الحضور</strong><small>آخر سبعة أيام</small></div><TrendingUp size={18} /></div><div className="bars">{[42, 58, 48, 76, 62, 86, 71].map((height, index) => <div className="bar-item" key={index}><span style={{ height: `${height}%` }} /><small>{["س", "ح", "ن", "ث", "ر", "خ", "ج"][index]}</small></div>)}</div></div></div></LifeShell>; }

export function Projects() { const [projects, setProjects] = useLocalList<{ id: string; name: string; progress: number; detail: string }>("aba-projects", [{ id: "p1", name: "نظام التشغيل الشخصي", progress: 78, detail: "تصميم وتجهيز" }, { id: "p2", name: "مسار اللغة الألمانية", progress: 42, detail: "المستوى A2" }]); return <LifeShell title="المشاريع" eyebrow="حوّل الرؤية إلى مسار"><div className="page-stack"><PageIntro kicker="غرفة المشاريع" title="كل مشروع له خطوة تالية." description="رؤى كبيرة، مقسمة إلى تقدم يمكن رؤيته." icon={FolderKanban} tone="blue"><button className="primary-button" onClick={() => { setProjects((current) => [{ id: createId(), name: "مشروع جديد", progress: 0, detail: "أضف الخطوة الأولى" }, ...current]); toast("أضيف مشروع جديد"); }}><Plus size={17} />مشروع جديد</button></PageIntro><div className="project-grid">{projects.map((project) => <div className="panel project-card" key={project.id}><div className="project-icon"><FolderKanban size={19} /></div><div className="project-title"><strong>{project.name}</strong><small>{project.detail}</small></div><span className="project-progress">{project.progress}%</span><div className="progress-track"><span style={{ width: `${project.progress}%` }} /></div><button className="text-button" onClick={() => setProjects((current) => current.map((item) => item.id === project.id ? { ...item, progress: Math.min(100, item.progress + 10) } : item))}>أضف تقدمًا <ChevronLeft size={15} /></button></div>)}</div></div></LifeShell>; }

export function Assistant() { const [messages, setMessages] = useLocalList<{ id: string; from: "me" | "bot"; text: string }>("aba-assistant", [{ id: "a1", from: "bot", text: "أهلًا بك. ما الشيء الذي تريد أن تعطيه مساحة اليوم؟" }]); const [input, setInput] = useState(""); const send = () => { if (!input.trim()) return; const text = input.trim(); setMessages((current) => [...current, { id: createId(), from: "me", text }, { id: createId(), from: "bot", text: "سأحتفظ بها كخطوة واضحة: ابدأ بالأصغر، وحدد وقتًا قصيرًا لها." }]); setInput(""); }; return <LifeShell title="مساعدي" eyebrow="فكرة أو قرار أو خطوة"><div className="page-stack"><PageIntro kicker="رفيق التفكير" title="اسأل، رتّب، ثم ابدأ." description="محادثة محلية خفيفة تحفظها في متصفحك وتساعدك على تحويل الضباب إلى خطوة." icon={Bot} tone="cyan" /><div className="assistant-panel"><div className="chat-window">{messages.map((message) => <div className={`chat-bubble ${message.from}`} key={message.id}>{message.text}</div>)}</div><div className="chat-compose"><input value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => event.key === "Enter" && send()} placeholder="اكتب ما يدور في بالك..." /><button className="primary-button" onClick={send}><MessageCircle size={16} />إرسال</button></div></div></div></LifeShell>; }

export function Deutsch() { const words = [{ word: "Guten Morgen", meaning: "صباح الخير" }, { word: "Danke", meaning: "شكرًا" }, { word: "Wie geht's?", meaning: "كيف حالك؟" }]; const [index, setIndex] = useState(0); return <LifeShell title="Deutsch lernen" eyebrow="تعلم قليلًا كل يوم"><div className="page-stack"><PageIntro kicker="مسار اللغة" title="Eine Sprache. Ein Schritt." description="جملة واحدة اليوم، ثقة أكبر غدًا." icon={Languages} tone="blue"><span className="progress-pill">A2 · 38%</span></PageIntro><div className="language-card"><span className="language-orb"><Languages size={24} /></span><small>بطاقة اليوم</small><h2>{words[index].word}</h2><p>{words[index].meaning}</p><button className="primary-button" onClick={() => setIndex((current) => (current + 1) % words.length)}>بطاقة جديدة <ChevronLeft size={15} /></button></div><div className="lesson-grid"><div className="panel lesson-item"><BookOpen size={18} /><strong>درس قصير</strong><small>أكمل 5 دقائق</small><span>12 دقيقة</span></div><div className="panel lesson-item"><Star size={18} /><strong>مراجعة الكلمات</strong><small>8 كلمات تنتظر التكرار</small><span>ابدأ الآن</span></div></div></div></LifeShell>; }

export function Vault() { const [locked, setLocked] = useState(true); return <LifeShell title="الخزانة" eyebrow="خصوصيتك أولًا"><div className="page-stack"><PageIntro kicker="المساحة الخاصة" title="أشياء لا يراها إلا أنت." description="ملاحظات وحسابات حساسة محفوظة محليًا في هذا المتصفح." icon={LockKeyhole} tone="violet"><ShieldCheck size={18} className="tone-emerald" /></PageIntro><div className="vault-card"><div className="vault-lock"><LockKeyhole size={30} /><strong>{locked ? "الخزانة مقفلة" : "الخزانة مفتوحة"}</strong><small>{locked ? "افتحها لعرض العناصر الخاصة" : "تأكد من إغلاقها بعد الانتهاء"}</small></div><button className="primary-button violet" onClick={() => setLocked((value) => !value)}>{locked ? "فتح الخزانة" : "قفل الخزانة"}</button></div>{!locked && <div className="list-panel"><div className="task-row"><span className="task-check checked"><Check size={15} /></span><div className="task-main"><strong>مساحة خاصة جديدة</strong><small>يمكنك إضافة محتوى عند ربط مخزن آمن خاص بك.</small></div></div></div>}</div></LifeShell>; }

export function VoiceTask() { const [recording, setRecording] = useState(false); return <LifeShell title="مهمة صوتية" eyebrow="قلها، وسنضعها في مسارك"><div className="page-stack"><PageIntro kicker="التقاط سريع" title="لا تدع الفكرة تختفي." description="هذه النسخة تجهز واجهة التسجيل محليًا؛ ربط خدمة تحويل الصوت إلى نص اختياري عبر متغيرات البيئة." icon={Mic} tone="blue" /><div className={`voice-card ${recording ? "recording" : ""}`}><span className="voice-ring"><Mic size={30} /></span><h2>{recording ? "أستمع الآن..." : "اضغط وابدأ الكلام"}</h2><p>{recording ? "اضغط مرة أخرى لإنهاء التسجيل" : "صف المهمة كما تقولها لصديق"}</p><button className={`primary-button ${recording ? "danger-button" : ""}`} onClick={() => setRecording((value) => !value)}>{recording ? <Pause size={16} /> : <Mic size={16} />}{recording ? "إنهاء التسجيل" : "بدء التسجيل"}</button></div></div></LifeShell>; }

export function Social() { const [liked, setLiked] = useState(false); return <LifeShell title="مساحتي الاجتماعية" eyebrow="شارك ما يستحق"><div className="page-stack"><PageIntro kicker="المحتوى الاجتماعي" title="علاقات أخف، وحضور أصدق." description="مساحة تجريبية قابلة للتوسعة مع الحفاظ على خصوصيتك." icon={Heart} tone="pink" /><div className="social-post panel"><div className="post-head"><span className="avatar">هـ</span><div><strong>هير محمود</strong><small>منذ ساعة · مساحتي</small></div><MoreHorizontal size={18} /></div><p>أجمل ما في اليوم أن نعرف متى نبطئ، ومتى نأخذ خطوة صغيرة إلى الأمام.</p><div className="post-actions"><button onClick={() => setLiked((value) => !value)} className={liked ? "liked" : ""}><Heart size={16} fill={liked ? "currentColor" : "none"} />{liked ? "أعجبتني" : "إعجاب"}</button><button><MessageCircle size={16} />تعليق</button></div></div></div></LifeShell>; }

export function More() { const [, navigate] = useLocation(); const links = [{ href: "/analytics", title: "إيقاعك", detail: "تحليلات لطيفة", icon: Activity }, { href: "/projects", title: "المشاريع", detail: "رؤى وخطوات", icon: FolderKanban }, { href: "/voice-task", title: "مهمة صوتية", detail: "التقاط سريع", icon: Mic }, { href: "/vault", title: "الخزانة", detail: "مساحة خاصة", icon: LockKeyhole }, { href: "/social", title: "مساحتي الاجتماعية", detail: "حضور أصدق", icon: Heart }]; return <LifeShell title="المزيد" eyebrow="أدواتك في مكان واحد"><div className="page-stack"><PageIntro kicker="مساحات إضافية" title="اختر المساحة التي تحتاجها." description="كل أداة هنا تخدم إيقاعًا واضحًا في حياتك." icon={MoreHorizontal} tone="violet" /><div className="more-grid">{links.map((item) => <button className="more-card" key={item.href} onClick={() => navigate(item.href)}><span className="more-icon"><item.icon size={20} /></span><span><strong>{item.title}</strong><small>{item.detail}</small></span><ChevronLeft size={16} /></button>)}</div><div className="panel local-note"><ShieldCheck size={20} /><div><strong>نسخة Web مستقلة</strong><p>بيانات هذه النسخة محفوظة في متصفحك. يمكنك نقل المشروع وتشغيله من أي جهاز دون الاعتماد على Manus.</p></div></div></div></LifeShell>; }

export function MobileAuth() { const [, navigate] = useLocation(); return <LifeShell title="ملفي" eyebrow="مساحتك الخاصة"><div className="page-stack"><div className="profile-hero panel"><span className="profile-avatar">هـ</span><span className="eyebrow">وضع محلي</span><h1>هير محمود</h1><p>هذه نسخة مستقلة تعمل ببيانات المتصفح ولا تحتاج تسجيل دخول خارجي.</p><button className="primary-button" onClick={() => navigate("/")}>العودة للرئيسية</button></div><div className="panel settings-list"><div><strong>الخصوصية</strong><small>لا توجد مفاتيح أو رموز دخول داخل المشروع.</small></div><ShieldCheck size={20} /></div></div></LifeShell>; }

export function NotFound() { const [, navigate] = useLocation(); return <LifeShell title="غير موجود" eyebrow="نعود بك إلى المسار"><div className="empty-page"><Sparkles size={30} /><h1>هذه المساحة غير موجودة</h1><p>ربما تغيّر المسار، لكن يومك ما زال هنا.</p><button className="primary-button" onClick={() => navigate("/")}>الرئيسية</button></div></LifeShell>; }

function PageIntro({ kicker, title, description, icon: Icon, tone, children }: { kicker: string; title: string; description: string; icon: typeof Sparkles; tone: string; children?: React.ReactNode }) { return <section className={`page-intro ${tone}`}><div className="intro-icon"><Icon size={21} /></div><div className="intro-copy"><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{description}</p></div>{children && <div className="intro-action">{children}</div>}</section>; }
function StatCard({ icon: Icon, label, value, detail, tone }: { icon: typeof Activity; label: string; value: string; detail: string; tone: string }) { return <div className={`stat-card ${tone}`}><span className="stat-icon"><Icon size={18} /></span><small>{label}</small><strong>{value}</strong><em>{detail}</em></div>; }
function AreaCard({ href, icon: Icon, title, detail, tone, navigate }: { href: string; icon: typeof Activity; title: string; detail: string; tone: string; navigate: (href: string) => void }) { return <button className={`area-card ${tone}`} onClick={() => navigate(href)}><span className="area-icon"><Icon size={19} /></span><span><strong>{title}</strong><small>{detail}</small></span><ChevronLeft size={16} /></button>; }
function EmptyState({ title, text, icon: Icon }: { title: string; text: string; icon: typeof Activity }) { return <div className="empty-state"><Icon size={26} /><strong>{title}</strong><small>{text}</small></div>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="modal-backdrop" onMouseDown={onClose}><div className="form-modal" onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><strong>{title}</strong><button className="icon-button" onClick={onClose}><X size={17} /></button></div>{children}</div></div>; }
